# Generated by Django 3.1.5 on 2021-01-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20210123_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
